services:  # Определение сервисов (контейнеров), которые будут запущены.
  regression:  # Имя сервиса, можно использовать для обращения к нему.
    image: python:3.12.0a4-alpine3.17  # Базовый образ Python версии 3.12 на Alpine Linux.
    build:  # Инструкция для сборки Docker-образа.
      context: .  # Указывает, что контекст сборки находится в текущей директории.
      dockerfile: Dockerfile  # Используется файл Dockerfile из текущей директории.
    volumes:  # Привязка папок (volumes) между хостом и контейнером.
      - ./:/usr/workspace  # Текущая директория монтируется в контейнер в /usr/workspace.
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"
      # Команда, которая выполняется при запуске контейнера:
      # 1. `ls -la` - выводит список файлов в директории.
      # 2. `pytest` - запускает тесты с выводом подробностей (-sv) и сохраняет результаты в allure-results.
    working_dir: /usr/workspace  # Рабочая директория внутри контейнера.
    environment:  # Переменные окружения для контейнера.
      - LOGIN=${LOGIN}  # Переменная окружения LOGIN получает значение из переменной хоста (должна быть задана перед запуском).

